### PR TITLE
move to maven, remove non factionsuuid hooks to make it work with new…

### PR DESCRIPTION
**Pull request by dnyferguson**
… factionsuuid

### CODE REVIEW

**Comment by dnyferguson** [comment]
my bad didnt mean to make this PR

**Comment by SubSide** [comment]
I can't remove this PR on my end.
Besides that, I don't see a reason why you'd move away from my package name xP
And I discourage you to rename it to something as generic as java.main. I suggest you read more into java packages for this.

**Comment by dnyferguson** [comment]
I know about packages, this was an unfonished scuffed PR that wasnt meant to go out. I thought you had to be the one to remove it because githubs docs said the owner of the repo was the only person able to

**Comment by SubSide** [comment]
Hmm, I did see this, maybe you can give that a try:
https://stackoverflow.com/a/63405794

**Comment by dnyferguson** [comment]
Their support told me that if you explicitly state you are fine with them deleting it by commenting on here, they will delete it

**Comment by SubSide** [comment]
I hereby state that I'm completely fine with this pull-request being deleted by GitHub staff  ;-)

**Pull request closed without merging**
